### ISSUE TITLE
Application crashes on missing GID

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/quota_notifier#219]
Occasionally the application will crash with the following log message:

```
   ERROR | 2023-04-06 07:03:00,815 | 'getgrgid(): gid not found: ####'
Traceback (most recent call last):
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/cli.py", line 122, in execute
    cls.run(
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/cli.py", line 105, in run
    UserNotifier().send_notifications()
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/notify.py", line 286, in send_notifications
    self.notify_user(user)
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/notify.py", line 218, in notify_user
    quota_list = self.get_user_quotas(user)
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/notify.py", line 149, in get_user_quotas
    user_path /= user.group
  File "/opt/crc/pipx/opt/venvs/quota-notifier/lib64/python3.9/site-packages/quota_notifier/shell.py", line 82, in group
    return grp.getgrgid(self.gid).gr_name
KeyError: 'getgrgid(): gid not found: ####'
```

User's are being fetched using ` pwd.getpwall()` so the user (and their associated group) should exist.

**Comment by djperrefort** [comment]
In parallel to investigating whether there is anything special about the user triggering the problem, this issue is also motivation to improve error handling in the application. If there is a problem notifying a user, the application should log the error and move on to the next one.

**Comment by djperrefort** [comment]
Just a follow up now that this is running in production. I checked the logs this morning and everything seems to be working appropriately.
